{
 "title": "HTTP Request/Response",
 "time": { "from": "2020-05-27T06:26:53.471Z", "to": "2020-05-27T08:29:23.082Z" },
 "panels": [
  {
   "title": "File system error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_filesystem_device_error" }
   ]
  },
  {
   "title": "Average CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu{job='node',mode='idle'}[5m]))) "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree" },
    { "expr": "node_memory_MemTotal" },
    { "expr": "node_memory_MemAvailable" }
   ]
  },
  {
   "title": "Total Response Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_response_size_bytes_sum" }
   ]
  },
  {
   "title": "GET Method",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "count(http_requests_total{method=\"get\"})"
    },
    {}
   ]
  },
  {
   "title": "404 Error",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(http_requests_total{code=\"400\"})"
    }
   ]
  },
  {
   "title": "Total http rate count ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_total" },
    {}
   ]
  }
 ]
}