{
 "title": "CitiusTech Real time Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Alerts",
   "type": "citiustech-ct-alerts-table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "time() - (ALERTS + ignoring(alertstate) group_left() ALERTS_FOR_STATE) + 1"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(ALERTS{})" }
   ]
  },
  {
   "title": "Alerts in past 24hrs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(ALERTS_FOR_STATE[24h]) + 1)"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Count",
   "type": "graph",
   "description": "\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(method,status,job,instance)(rate(http_server_requests_seconds_count{status=~\"^3..\",uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "{{instance,job,method,status}}"
    },
    { "legendFormat": "{{instance,job,method,status}}" },
    {
     "expr": "sum by(method,status,job,instance)(rate(http_server_requests_seconds_count{status=~\"^5..\",uri!~\".*actuator.*\"}[1m]))",
     "legendFormat": "{{instance,job,method,status}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "description": "Per second average rate of response time over 1 minute",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{ exception=\"None\", uri!~\".*actuator.*\"}[1m]) / rate(http_server_requests_seconds_count{ exception=\"None\", uri!~\".*actuator.*\"}[1m]) ",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Request Sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{exception=\"None\", uri!~\".*actuator.*\"}[5m])\r",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"spring-boot-angular-jboss\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total) by (cpu))"
    }
   ]
  },
  {
   "title": "High User and System CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total[5m]))"
    }
   ]
  },
  {
   "title": "Memory Used by Various Jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "(process_virtual_memory_bytes{}[5m])",
     "legendFormat": "Processes virtual memory size in bytes {{job}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"spring-boot-angular-jboss\"}*1000"
    }
   ]
  },
  {
   "title": "Processor Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(node_cpu_seconds_total{mode=~\"user|nice|system|irq|softirq|steal|idle|iowait\"}) by (instance, job)) - (sum(node_cpu_seconds_total{mode=~\"idle|iowait\"}) by (instance, job))) / (sum(node_cpu_seconds_total{mode=~\"user|nice|system|irq|softirq|steal|idle|iowait\"}) by (instance, job)) * 100",
     "legendFormat": "{{instance,job}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{}) by (cpu))"
    }
   ]
  },
  {
   "title": "Max Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(process_virtual_memory_max_bytes{}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "step" },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "SWAP Memory",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{}) / (node_memory_SwapTotal_bytes{})) * 100"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 "
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Filesystem space available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Available"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Size"
    }
   ]
  },
  {
   "title": "File Nodes Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - File nodes total"
    }
   ]
  },
  {
   "title": "File Nodes Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - Free file nodes"
    }
   ]
  },
  {
   "title": "Host out of disk space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 "
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Network Traffic Received in Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance,job) (irate(node_network_receive_bytes_total[5m])) / 1024 / 1024 ",
     "legendFormat": "{{device}} - Receive"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{}[5m])"
    }
   ]
  },
  {
   "title": "Network Receives Errors Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total[5m]) "
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "No. of user errors/sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(mssql_user_errors[5m])", "legendFormat": "User_errors" }
   ]
  },
  {
   "title": "Number of Transact-SQL",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mssql_batch_requests{}" }
   ]
  },
  {
   "title": "No. of kill connection errors",
   "type": "stat",
   "description": "No. of kill connection errors",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mssql_kill_connection_errors{})"
    }
   ]
  },
  {
   "title": "No. of active connections",
   "type": "stat",
   "description": "No. of active connections",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mssql_connections{database=\"users_database\"}",
     "legendFormat": "Active Connections"
    }
   ]
  },
  {
   "title": "Write Stall Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall{database=\"users_database\",type=\"write\"}",
     "legendFormat": "Write Stall Time (ms)"
    }
   ]
  },
  {
   "title": "Read Stall Time ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mssql_io_stall{database=\"users_database\",type=\"read\"}",
     "legendFormat": "Read Stall Time (ms)"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(mssql_deadlocks{}[5m])" }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "No. of actions on docker daemon",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(engine_daemon_container_actions_seconds_bucket{}[15m]))",
     "legendFormat": "{{action}} "
    }
   ]
  },
  {
   "title": "No. of CPU for instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus" }
   ]
  },
  {
   "title": "Container health check",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(engine_daemon_health_checks_total[5m])"
    }
   ]
  },
  {
   "title": "Total failed health check",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(engine_daemon_health_checks_failed_total[5m])"
    }
   ]
  }
 ]
}