version: '2'
services:
  nginx:
    image: nginx
    ports:
     - '8080:80'
    container_name: nginx
    restart: always
    # network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html/
    # environment: 
    #   DISABLE_IPV6: 'true'