route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: test.rohitks@gmail.com
    from: test.rohitks@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "test.rohitks@gmail.com"
    auth_identity: "test.rohitks@gmail.com"
    auth_password: "<password>"
